import Head from "next/head";
import styles from "../styles/Home.module.css";
import Moralis from "moralis";
import { useMoralis, useWeb3Contract } from "react-moralis";
import { useEffect, useState } from "react";

export default function Home() {
  const { enableWeb3, isWeb3Enabled } = useMoralis();
  const [greetText, setGreetText] = useState("");
  const [greetContent, setGreetContent] = useState("");
  const [isLoading, setLoading] = useState(false);

  const ABI = [
    {
      inputs: [
        {
          internalType: "string",
          name: "_greeting",
          type: "string",
        },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      inputs: [],
      name: "greet",
      outputs: [
        {
          internalType: "string",
          name: "",
          type: "string",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "string",
          name: "_greeting",
          type: "string",
        },
      ],
      name: "setGreeting",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ];
  const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

  const readOptions = {
    abi: ABI,
    contractAddress,
    functionName: "greet",
  };

  const writeOptions = {
    abi: ABI,
    contractAddress,
    functionName: "setGreeting",
    params: {
      _greeting: greetContent,
    },
  };

  // Set Greeting
  const handleSetGreeting = async () => {
    setLoading(true);
    await Moralis.executeFunction(writeOptions);
    setLoading(false);
  };

  // Get Greeting
  const handleGetGreeting = async () => {
    const message = await Moralis.executeFunction(readOptions);
    console.log(
      "🚀 ~ file: index.js ~ line 79 ~ handleGetGreeting ~ message",
      message
    );
    setGreetText(message);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isWeb3Enabled ? (
          <>
            <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
              <div className="mb-4">
                <label
                  className="block text-gray-700 text-sm font-bold mb-2"
                  htmlFor="greetDesc"
                >
                  Greet Description:
                </label>
                <input
                  type="text"
                  onChange={(e) => setGreetContent(e.target.value)}
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  id="greetDesc"
                />
              </div>

              <div className="mb-4">
                <button
                  onClick={() => handleSetGreeting()}
                  type="button"
                  className="bg-indigo-600 text-white text-sm leading-6 font-medium py-2 px-3 rounded-lg"
                >
                  Set Greeting
                </button>
              </div>
            </form>

            <button
              onClick={() => handleGetGreeting()}
              type="button"
              className="bg-indigo-600 text-white text-sm leading-6 font-medium py-2 px-3 rounded-lg"
            >
              Get Greeting
            </button>

            {isLoading ? "Loading...." : "Loaded"}

            {greetText ? <h2>{greetText}</h2> : "...."}
          </>
        ) : (
          <button
            onClick={(e) => enableWeb3()}
            className="bg-indigo-600 text-white text-sm leading-6 font-medium py-2 px-3 rounded-lg"
          >
            Connect
          </button>
        )}
      </main>
    </div>
  );
}
